# Terminator bindings for tmux

# Split window (Ctrl + Shift + x -> Ctrl + X)
bind -n C-E split-window -h
bind -n C-O split-window -v

# Panel selection: Alt + Arrow keys
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
